events:
    only: false
colors:
    message: RED
    item: GOLD
    name: DARK_AQUA
monsters:
    ghast: Ghast
    slime: Slime
    monster: Monster
    zombie: Zombie
    pigzombie: PigZombie
    spider: Spider
    creeper: Creeper
    skeleton: Skeleton
    unknown: Unknown
    giant: Giant
    wolf: Wolf
log:
    files:
        data: death_data.log
        messages: death_messages.log
    time:
        format: MM/dd/yyyy HH:mm:ss z
        stamp: true
    data: true
    messages: true
