useID: false
sell: true
distance: 1
position: 'DOWN'
protection: true 

#protection - do you want to use anti-stealing protection?
#useID - use numerical ID's?
#sell - do you want to activate selling?
#distance - distance between the chest and the sign
#position - position of the chest, goo.gl/YItRO

# prefix will be dispayed at the beggining of every message.
# you can use terms lile <buyer>, <amount> or <item> in messages however
#	 only certain messagess offer this.
#
#
# <buyer> - nick of the person who bought.
# <owner> - nick of the person who own the shop.
# <amount> - amount of item
# <item> - name of item
# <money> - amount of money with iConomy currency
#
# You can always use hMod colors, like
# &1, &f etc...
# For example: This is my&6 golden text.

# somebodyBoughtFromYou - is dispayed to you when buyer successfully bought from your shop
#               You can use: <buyer> <amount> <item> and <cost>
# youBought - is dispayed to you bought something
#               You can use: <owner> <amount> <item> and <cost>
# yourBalance - displays your current balance 
#               You can use: <money>
# inventoryFull - you would never guess but it is show when you have full inventory
# noEnoughMoney - lacking in money?
# outOfStock - displayed when you are trying to buy from shop that is empty
# yourShopIsOutOfStock - displayed when somebody is trying to buy from your shop which is empty
# cantBuyFromYourOwnShop - displayed when you are trying to buy from your own shop
# cantSellToYourOwnShop - displayed when you are trying to sell to your own shop
# shopCreated - displayed when you have craten new shop successfully
# modeBuy - displayed when player switches to buying
# modeBuy - displayed when player switches to selling
#stealing - displayed when player tries to destroy someone's shop
#notEnoughMoneyForShop - seller has not enough money to buy items from you.
#tmpFix - displayed when sign update occurs
#sellerHasNoAcc - displayed if seller has no iConomy account
#noSelling - displayed when seller doesn't want you to sell your items there
#noBuying - displayed when seller doesn't want you to buy items there
#oldSign - sign is in an old format
#MAXIMUM OF 55 CHARACTERS WITH PREFIX!
lang:
    prefix: '&a[Shop] &f'
    somebodyBoughtFromYou: '<buyer> bought <amount> <item> for <cost>!'
    youBought: 'You bought <amount> <item> from <owner>.'
    yourBalance: 'After purchasing you have <money> left.'
    inventoryFull: 'Your inventory is full!'
    noEnoughMoney: "You don't have enough money!"
    outOfStock: 'This shop is out of stock!'
    yourShopIsOutOfStock: 'Your shop is out of stock!'
    cantBuyFromYourOwnShop: "You can't buy from your own shop!"
    cantSellToYourOwnShop: "You can't sell to your own shop!"
    shopCreated: 'Your shop has been successfully created!'
    chestFull: 'This chest is full!'
    somebodySoldYou: '<buyer> sold <amount> <item> for <cost>!'
    youSold: 'You sold <amount> <item> for <cost>.'
    notEnough: 'You have not enough items to sell!'
    modeSell: 'Mode set to selling!'
    modeBuy: 'Mode set to buying!'
    stealing: "Don't steal!"
    notEnoughMoneyForShop: "Seller has not enough money!"
    tmpFix: "Updating item on the sign!"
    sellerHasNoAcc: "Seller's account doesn't exist!"
    noSelling: "You can't sell to this shop!"
    noBuying: "You can't buy from this shop!"
    oldSign: "Sign is in old format, please update!"