online-on-join: true
motd: |
    `YWelcome to cheeseburgervacation.com - 1.4`
    `YMumble Server: ny2.mumblevoice.com:64821`
    `2/r/cheeseburgervacation to join, discuss & share.
rules: |
    - Be courteous and respect others.
    - Don't use any tools to give you an unfair advantage.
